-------------------BadStatusLine: ''-----------------------
[2016-12-07 21:04:05,969] [ERROR] apk_report_run.py:111 27495dc3bdf5a6d9f3d190a74215d4c8
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 63, in basic_info_collect
    init_ip_attribution = get_ip_attribution(init_ip)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/file_hash.py", line 134, in get_ip_attribution
    f = urllib2.urlopen(url).read()
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python27/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

-------------------error: [Errno 104] Connection reset by peer-----------------------
[2016-12-07 19:40:57,710] [ERROR] apk_report_run.py:111 5dcae41d211c802aa898b0bf44230beb
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 64, in basic_info_collect
    target_ip_attribution = get_ip_attribution(target_ip)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/file_hash.py", line 134, in get_ip_attribution
    f = urllib2.urlopen(url).read()
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python27/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python27/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[2016-12-07 19:50:16,178] [ERROR] apk_report_run.py:111 1bf9fc0669d51cc00aee0af098670eb6
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 63, in basic_info_collect
    init_ip_attribution = get_ip_attribution(init_ip)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/file_hash.py", line 134, in get_ip_attribution
    f = urllib2.urlopen(url).read()
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python27/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python27/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[2016-12-07 19:54:40,463] [ERROR] apk_report_run.py:111 900e9c688190ddfbc61828c157752ae5
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 63, in basic_info_collect
    init_ip_attribution = get_ip_attribution(init_ip)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/file_hash.py", line 134, in get_ip_attribution
    f = urllib2.urlopen(url).read()
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python27/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python27/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[2016-12-07 20:33:08,329] [ERROR] apk_report_run.py:111 bcc0a99add4141fb80b3985dca95a592
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 64, in basic_info_collect
    target_ip_attribution = get_ip_attribution(target_ip)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/file_hash.py", line 134, in get_ip_attribution
    f = urllib2.urlopen(url).read()
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python27/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python27/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[2016-12-07 21:01:01,370] [ERROR] apk_report_run.py:111 e4aacc5f059a25d167cf4a99744255f8
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 64, in basic_info_collect
    target_ip_attribution = get_ip_attribution(target_ip)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/file_hash.py", line 134, in get_ip_attribution
    f = urllib2.urlopen(url).read()
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python27/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python27/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[2016-12-07 22:01:26,775] [ERROR] apk_report_run.py:111 da0fda638a7964454c02e387e4e63c25
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 63, in basic_info_collect
    init_ip_attribution = get_ip_attribution(init_ip)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/file_hash.py", line 134, in get_ip_attribution
    f = urllib2.urlopen(url).read()
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python27/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python27/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python27/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python27/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer

-------------------BadZipfile: File is not a zip file-----------------------
[2016-12-07 21:25:04,658] [ERROR] apk_report_run.py:111 6a06670aeb8fd04c1f254f0763916002
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-07 22:42:48,395] [ERROR] apk_report_run.py:111 2d932b11b4698468e6740f007443cbf2
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-08 00:37:13,034] [ERROR] apk_report_run.py:111 966cec0052bd2ae2788c3dea4bead880
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-08 00:40:39,331] [ERROR] apk_report_run.py:111 f139361e8597e28b802fb1323e47eef9
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-08 00:41:09,891] [ERROR] apk_report_run.py:111 ccd480aad6fda544551adda8428b74c1
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-08 02:28:52,945] [ERROR] apk_report_run.py:111 154b4dc57e1a9079179f6b24b6f52941
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-08 18:14:39,383] [ERROR] apk_report_run.py:111 9515d0aec9c218c5bb35c53bd3f3cb41
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-09 23:01:18,322] [ERROR] apk_report_run.py:111 676e8d8893437e32822d1c9712253b3b
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-10 23:42:10,864] [ERROR] apk_report_run.py:111 f844f438c57bde81151c15f1fa73043d
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-11 07:49:38,031] [ERROR] apk_report_run.py:111 b3f650db4dc5acfbe03c9df01ee6c856
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-11 12:12:45,403] [ERROR] apk_report_run.py:111 e00629ed71f19b2a2b7c758b1a9a90b2
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-11 20:01:31,687] [ERROR] apk_report_run.py:111 2dc308f7fdfaf91bf61669c2c4e1d372
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-11 20:21:01,681] [ERROR] apk_report_run.py:111 e4e5d9c2ac1800f6dcce405509c73678
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-11 21:23:07,378] [ERROR] apk_report_run.py:111 a6617f4fe214f12c1df37e311898bad9
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-11 21:30:22,458] [ERROR] apk_report_run.py:111 83e0ec8c84ba9e9b40ae25e860fb84bd
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-11 22:00:06,438] [ERROR] apk_report_run.py:111 484e78f4680c8304cdb471e671f4120f
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-11 23:03:12,982] [ERROR] apk_report_run.py:111 03d5b5660f95af12fde02c0f7621559b
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-12 07:01:36,495] [ERROR] apk_report_run.py:111 7ada2aa8f88f8e262c9264eef0364645
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
[2016-12-12 08:35:46,654] [ERROR] apk_report_run.py:111 374b9fe85801c7cac7c613a2043cef09
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

-------------------TypeError: exceptions must be old-style classes or derived from BaseException, not str-----------------------
[2016-12-08 04:56:14,002] [ERROR] apk_report_run.py:111 42775ebd60e861acbaa67ecf09bdb4c3
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 72, in __init__
    self.xml[i] = minidom.parseString(AXMLPrinter(self.zip.read(i)).getBuff())
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/axmlprinter.py", line 37, in __init__
    _type = self.axml.next()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/axmlparser.py", line 59, in next
    self.doNext()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/axmlparser.py", line 99, in doNext
    raise("ooo")
TypeError: exceptions must be old-style classes or derived from BaseException, not str

-------------------IndexError: list index out of range-----------------------
[2016-12-07 20:23:28,493] [ERROR] apk_report_run.py:111 d85e1e9388fe6d1e696a2f13f3457ab4
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 56, in basic_info_collect
    min_sdk,fit_sdk = apk_sdk_obj.parserSdkVersion()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 134, in parserSdkVersion
    tarSdkVersion = v.split('\"')[3]
IndexError: list index out of range
[2016-12-08 00:16:05,877] [ERROR] apk_report_run.py:111 170749d7c95179ca93347ee98628ab6b
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 56, in basic_info_collect
    min_sdk,fit_sdk = apk_sdk_obj.parserSdkVersion()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 132, in parserSdkVersion
    v = nodes[0].toxml()
IndexError: list index out of range
[2016-12-08 01:06:09,963] [ERROR] apk_report_run.py:111 5dc0bee60112ba2d4d8efb697e9093a0
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 56, in basic_info_collect
    min_sdk,fit_sdk = apk_sdk_obj.parserSdkVersion()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 134, in parserSdkVersion
    tarSdkVersion = v.split('\"')[3]
IndexError: list index out of range
[2016-12-08 02:27:50,357] [ERROR] apk_report_run.py:111 7ca2b30470edc579b6676f29bc5a5244
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 56, in basic_info_collect
    min_sdk,fit_sdk = apk_sdk_obj.parserSdkVersion()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 134, in parserSdkVersion
    tarSdkVersion = v.split('\"')[3]
IndexError: list index out of range

-------------------error: unpack requires a string argument of length 4-----------------------
[2016-12-07 20:43:31,580] [ERROR] apk_report_run.py:111 be99a0d108527063bf16c12701d6e5c0
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 853, in _RealGetContents
    x._decodeExtra()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 388, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
error: unpack requires a string argument of length 4
[2016-12-08 00:05:27,024] [ERROR] apk_report_run.py:111 af9a1dd8e0d7397f0bf600390d1f78d9
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 853, in _RealGetContents
    x._decodeExtra()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 388, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
error: unpack requires a string argument of length 4
[2016-12-09 18:04:58,063] [ERROR] apk_report_run.py:111 9054b1cc620dff012f610b9d0e664438
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 853, in _RealGetContents
    x._decodeExtra()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 388, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
error: unpack requires a string argument of length 4
[2016-12-10 16:27:19,655] [ERROR] apk_report_run.py:111 99f244a9c56ad0dc63c13a21da245870
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 20, in get_xml
    obj = APK(self.apk_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 65, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw))
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 853, in _RealGetContents
    x._decodeExtra()
  File "/usr/local/python27/lib/python2.7/zipfile.py", line 388, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
error: unpack requires a string argument of length 4

-------------------UnicodeDecodeError: 'utf8' codec can't decode byte 0xc7 in position 435: invalid continuation byte-----------------------
[2016-12-07 23:16:19,405] [ERROR] apk_report_run.py:111 23815334c285bbcbf84803b768d578ec
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 68, in basic_info_collect
    out = self.apk_code + '|' + apk_file_name + '|' + md5 + '|' + sha1 + '|' + sha256  + '|' + sha512 + '|' + self.first_found_time + '|' + last_found_time + '|' + short_url + '|' + long_url + '|' + self.sms_content + '|' + virus_score + '|' + virus_grade + '|' + apk_analyze_run_time + '|' + min_sdk +   '|' + fit_sdk + '|' + init_ip + '|' + init_ip_attribution + '|' + target_ip + '|' + target_ip_attribution + '|' + str(apk_file_size) + '|' + str(apk_source_file_num) + '\n'
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc7 in position 435: invalid continuation byte

-------------------TypeError: string indices must be integers, not str-----------------------
[2016-12-07 19:49:29,048] [ERROR] apk_report_run.py:111 eb130f6a05e035ceaf950f1360581131
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 64, in basic_info_collect
    target_ip_attribution = get_ip_attribution(target_ip)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/file_hash.py", line 137, in get_ip_attribution
    ret.append(s['data']['ip'])
TypeError: string indices must be integers, not str

-------------------IOError: [Errno 2] No such file or directory: 'data/008cf307e43662886a9bf85620e5d4d9/code_key.txt'-----------------------
[2016-12-07 22:53:32,000] [ERROR] apk_report_run.py:111 008cf307e43662886a9bf85620e5d4d9
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 59, in basic_info_collect
    virus_score = virus_apk_tell_obj.virus_tell()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/tell_virus_apk.py", line 107, in virus_tell
    value = self.codeblock_evaluation()+self.permis_evaluation() + self.act_evaluation()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/tell_virus_apk.py", line 60, in codeblock_evaluation
    senderCouter = self.item_couter(sender)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/tell_virus_apk.py", line 34, in item_couter
    code_key_list = self.get_code_key()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/tell_virus_apk.py", line 43, in get_code_key
    with open(self.code_key_path,'r') as f:
IOError: [Errno 2] No such file or directory: 'data/008cf307e43662886a9bf85620e5d4d9/code_key.txt'

-------------------IOError: [Errno 2] No such file or directory: '/opt/smmc/apk_parse/apk_source/fe7d2790cb50c81794bff5fddae77ac6/AndroidManifest.xml'-----------------------
[2016-12-10 18:14:59,006] [ERROR] apk_report_run.py:111 fe7d2790cb50c81794bff5fddae77ac6
Traceback (most recent call last):
  File "apk_report_run.py", line 89, in apk_analyze_run
    apk_report.run()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 53, in run
    self.parser_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/main_info_sort.py", line 45, in parser_xml
    obj2 = XmlParser(self.apk_path,self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 16, in __init__
    self.get_xml()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/xml_parser.py", line 21, in get_xml
    obj.save_copy_xml(self.xml_path)
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/module/axmlparserpy/apk.py", line 87, in save_copy_xml
    with open(path,'w+') as f:
IOError: [Errno 2] No such file or directory: '/opt/smmc/apk_parse/apk_source/fe7d2790cb50c81794bff5fddae77ac6/AndroidManifest.xml'

-------------------UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 447: invalid continuation byte-----------------------
[2016-12-09 13:21:39,695] [ERROR] apk_report_run.py:111 6484b70aa15f846fa7de225a5483dbdd
Traceback (most recent call last):
  File "apk_report_run.py", line 99, in apk_analyze_run
    apk_basic_obj.basic_info_collect()
  File "/opt/smmc/apk_parse/entire_apk_report_run/sort/basic_info_sort.py", line 68, in basic_info_collect
    out = self.apk_code + '|' + apk_file_name + '|' + md5 + '|' + sha1 + '|' + sha256  + '|' + sha512 + '|' + self.first_found_time + '|' + last_found_time + '|' + short_url + '|' + long_url + '|' + self.sms_content + '|' + virus_score + '|' + virus_grade + '|' + apk_analyze_run_time + '|' + min_sdk +   '|' + fit_sdk + '|' + init_ip + '|' + init_ip_attribution + '|' + target_ip + '|' + target_ip_attribution + '|' + str(apk_file_size) + '|' + str(apk_source_file_num) + '\n'
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 447: invalid continuation byte

